# -*- encoding : utf-8 -*-

module Const
  STATUS_UNRANKED=0
  STATUS_UNRECEIVED=0
  STATUS_UNSOLVED=1
  STATUS_UNCOMPLETED=1
  STATUS_UNISSUED=1
  STATUS_SOLVED=2
  STATUS_TO_TEST=2
  STATUS_COMPLETED=3
  STATUS_ISSUED=3
  STATUS_CLOSED=3
  STATUS_PASSED=5
  STATUS_SUSPEND=8
  STATUS_CANCELED=9
end
